version: '3.4'

services:
  chain-client-alpha:
    image: stbmorgan/js-blockchain
    network_mode: bridge
    environment:
      - HTTP_PORT=3001
      - P2P_PORT=5001
    ports:
      - "3001:3001"
      - "5001:5001"

  chain-client-bravo:
    image: stbmorgan/js-blockchain
    network_mode: bridge
    environment:
      - HTTP_PORT=3002
      - P2P_PORT=5002
      - PEERS=ws://172.17.0.2:5001
    ports:
      - "3002:3002"
      - "5002:5002"
    depends_on: 
      - chain-client-alpha



